steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - piamidy_functions
  - --entry-point=org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
  - --runtime=java17
  - --trigger-http
  - --source=src/main/java 
  - --memory=256MB
  - --allow-unauthenticated