steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - gcloud
  - functions
  - deploy
  - hello
  - --entry-point=com.zekisoft.PiamidyFunctions
  - --region=us-central1
  - --source=.
  - --runtime=java17
  - --trigger-http
  - --memory=256MB
  - --allow-unauthenticated