steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello
#  - --entry-point=org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
  - --region=us-central1
  - --source=.
  - --runtime=java17
  - --trigger-http
  - --memory=256MB
  - --allow-unauthenticated